Import('*')

libs = Glob('lib/*.[cs]') 
common = Glob('common/*.c')
i686src = Glob('i686/*.[sc]')
testsrc = Glob('test/*.c')

includepaths = [ '.', 'include/', 'lib/']


sources = libs
sources += common

if architecture == "i686":
  sources.extend(i686src)
  includepaths.append('i686/')
  env.Append(CFLAGS=" -fstack-protector")
if architecture == "test":
  sources.extend(testsrc)
#The two extra defines are because scons doesn't appear to do pkg-config right
#so OpenBSD doesn't work
  env.Append(CFLAGS="-ggdb -I/usr/local/include -L/usr/local/lib -DHOSTED")

objects = []
for item in sources:
  objects += env.Object(item, CPPPATH=includepaths)

if architecture == "test":
  env.ParseConfig('pkg-config --cflags --libs check')
  env.Program('kernel', objects)
else:
  env.Loader('loader', env.Object('i686/loader/loader.c', CPPPATH=includepaths))
  env.Kernel('kernel', objects)
