SRCS+= ${SRCROOT}/common/mutex.c \
			 ${SRCROOT}/common/physmem.c \
			 ${SRCROOT}/common/address_space.c \
			 ${SRCROOT}/common/thread.c \
			 ${SRCROOT}/common/scheduler.c \
			 ${SRCROOT}/common/virtmem.c \
			 ${SRCROOT}/common/slab.c
